name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: stylelint-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          stylelint_config: 'stylelint-config-recommended'
      - name: stylelint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
      - name: stylelint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
